version: 3
groups:
  ide-committers:
    reviews:
      required: 1
    reviewers:
      teams:
        - ide
    conditions:
      - "'needs:review-ide' in labels"
  core-committers:
    reviews:  
      required: 1
    reviewers:      
      teams:
        - core
    conditions:
      - "base.ref == 'master'"
  lingua-committers:
    reviews:
      required: 1
    reviewers:      
      teams:
        - lingua
    conditions:
      - "'needs:review-lingua' in labels"
  core-interns:
    reviews:
      required: 1
    reviewers:
      teams:
        - core-interns
    conditions:
      - "'needs:review-core-interns' in labels"
